### ISSUE TITLE
CLIENT_MISSING_INTENTS

### ISSUE THREAD

**Issue by mrranger** [bountythebeast/NodeJS-PteroBot#1]
Hi, this is a pity, but the script does not work (
Can I fix it somehow?
/home/container/node_modules/discord.js/src/client/Client.js:544
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

**Comment by bountythebeast** [comment]
Most recent update should fix it, but please let me know if your still having an issue.

Cause: Main branch was unintentionally updated to Discord.JS-V13, while working to update the whole bot. This was not intended to be pushed to main yet, as the changes are very much in progress.

**Comment by bountythebeast** [comment]
Closing as its been a month... please feel free to reopen if you need further assistance.
